import dynamic from "next/dynamic";
import { saira, merienda } from './fonts';
import Image from "next/image";
import FallbackLoading from "@/components/FallbackLoading";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import Layout from "./components/layout/page";
import { Toaster } from 'sonner';
const AppProvidersWrapper = dynamic(() => import('@/components/wrappers/AppProvidersWrapper'));
import logoDark from '@/assets/images/logo.svg';
import 'aos/dist/aos.css';
import '@/assets/scss/style.scss';
import "./globals.css";

// const saira = Saira({
//   display: 'swap',
//   style: ['normal', 'italic'],
//   subsets: ['latin'],
//   weight: ['300' ,'400', '500', '700']
// });
export const metadata = {
  title: {
    template: '%s | Eduport - LMS, Education and Course Theme',
    default: ""
  },
  description: "Generated by create next app"
};
const splashScreenStyles = `
#splash-screen {
  position: fixed;
  top: 50%;
  left: 50%;
  background: white;
  display: flex;
  height: 100%;
  width: 100%;
  transform: translate(-50%, -50%);
  align-items: center;
  justify-content: center;
  z-index: 9999;
  opacity: 1;
  transition: all 0.5s ease;
  overflow: hidden;
}

#splash-screen.remove {
  animation: fadeout 0.3s forwards;
  z-index: 0;
}

@keyframes fadeout {
  to {
    opacity: 0;
    visibility: hidden;
    display: none;
  }
}
`;


export default function RootLayout({ children }) {

  return <html lang="en" className={`${saira.className} ${merienda.variable}`}>
    <head>
      <style suppressHydrationWarning>{splashScreenStyles}</style>
    </head>
    <body>
      <div id="splash-screen">
        <Image alt="Logo" width={355} height={83} src={logoDark} style={{
          height: '10%',
          width: 'auto'
        }} priority />
      </div>

      <NextTopLoader color="#4697ce" showSpinner={false} />
      <div id="__next_splash">
        <AppProvidersWrapper>
          <Suspense fallback={<FallbackLoading />}>
            <Layout>
              {children}
              <Toaster position="top-right" richColors />
            </Layout>
          </Suspense>
        </AppProvidersWrapper>
      </div>
    </body>

  </html>;
}
